import { useMemo, useState } from 'react';
import Icon from '../components/Icon.jsx';
import EventCard from '../components/EventCard.jsx';
import { filterEvents } from '../services/api.js';

export default function Dashboard({ events, loading, error, onRetry, options, preferences, personalized, filters, setFilters, savedOnly, savedIds, onSave, onOpen, onPreferences, onExplore }) {
  const [limit, setLimit] = useState(12);
  const available = savedOnly ? events.filter((event) => savedIds.has(event.id)) : events;
  const filtered = useMemo(() => filterEvents(available, filters), [available, filters]);
  const update = (key, value) => { setLimit(12); setFilters({ ...filters, [key]: value }); };
  const reset = () => { setLimit(12); setFilters({ search: '', campus: 'All Campuses', category: 'All categories', date: 'any', sort: 'relevance' }); };
  return <main className="section dashboard">
    <div className="dashboard-heading"><div><span className="eyebrow">{savedOnly ? 'KEEP THE GOOD THINGS CLOSE' : 'FIND YOUR NEXT CONNECTION'}</span><h1>{savedOnly ? 'Your saved events.' : 'A world of possibility.'}</h1><p>{savedOnly ? 'All the things you want to make time for, in one place.' : 'Follow your curiosity. There’s something here for you.'}</p></div><button className="button secondary" onClick={onPreferences}><Icon name="tune" size={17} />{personalized ? 'Edit preferences' : 'Personalize my feed'}</button></div>
    {personalized && !savedOnly && <div className="personalized-banner"><span className="personalized-icon"><Icon name="sparkle" /></span><div><strong>A little more you.</strong><p>Recommended for {preferences.major}{preferences.interests.length ? ` · ${preferences.interests.slice(0, 3).join(' · ')}${preferences.interests.length > 3 ? ' + more' : ''}` : ''}</p></div><span className="local-badge">Saved on this device</span></div>}
    <div className="filter-panel"><label className="search-field"><Icon name="search" size={20} /><input aria-label="Search events" placeholder="Search for your next thing…" maxLength={200} value={filters.search} onChange={(event) => update('search', event.target.value)} />{filters.search && <button onClick={() => update('search', '')} aria-label="Clear search"><Icon name="close" size={17} /></button>}</label><div className="filter-row"><label>Campus<select value={filters.campus} onChange={(event) => update('campus', event.target.value)}>{options.campuses.map((campus) => <option key={campus}>{campus}</option>)}</select></label><label>Category<select value={filters.category} onChange={(event) => update('category', event.target.value)}><option>All categories</option>{options.interests.map((interest) => <option key={interest}>{interest}</option>)}<option>Campus Life</option></select></label><label>When<select value={filters.date} onChange={(event) => update('date', event.target.value)}><option value="any">Any upcoming date</option><option value="today">Today</option><option value="week">Next 7 days</option><option value="month">Next 30 days</option></select></label><button className="reset-button" onClick={reset}>Reset filters</button></div></div>
    <div className="results-heading"><p role="status"><strong>{loading ? 'Finding' : filtered.length}</strong> {savedOnly ? 'saved ' : ''}events{filters.campus !== 'All Campuses' ? ` in ${filters.campus}` : ' to explore'}</p><label>Sort by <select aria-label="Sort events" value={filters.sort} onChange={(event) => update('sort', event.target.value)}><option value="relevance">Best match</option><option value="date">Soonest first</option></select></label></div>
    {loading ? <div className="card-grid" aria-label="Loading events">{[1,2,3,4,5,6].map((n) => <div key={n} className="skeleton-card" />)}</div> : error ? <div className="empty-state"><Icon name="globe" size={40} /><h2>We hit a little detour.</h2><p>{error}</p><button className="button primary" onClick={onRetry}>Try again</button></div> : filtered.length ? <><div className="card-grid">{filtered.slice(0, limit).map((event) => <EventCard key={event.id} event={event} saved={savedIds.has(event.id)} onSave={onSave} onOpen={onOpen} personalized={personalized} />)}</div>{filtered.length > limit && <button className="button secondary load-more" onClick={() => setLimit(limit + 12)}>Show more events <Icon name="arrow" size={17} /></button>}</> : <div className="empty-state"><span className="empty-icon"><Icon name={savedOnly ? 'bookmark' : 'search'} size={32} /></span><h2>{savedOnly && !available.length ? 'Your next plans start here.' : 'A little too specific?'}</h2><p>{savedOnly && !available.length ? 'Tap the bookmark on any event to keep it here for later.' : 'Try another search or open up your filters to discover more.'}</p><button className="button primary" onClick={savedOnly && !available.length ? onExplore : reset}>{savedOnly && !available.length ? 'Explore events' : 'Clear filters'}<Icon name="arrow" size={17} /></button></div>}
    <p className="results-footnote">{savedOnly && 'Saved events shown here are from your selected collection’s current listings. '}{personalized ? 'Match scores are based on keywords, not a prediction. All relevance levels are included.' : 'Add your preferences to see match scores and personalized recommendations.'} All times Eastern.</p>
  </main>;
}
